remote_theme: pmarsceill/just-the-docs
title: oxmysql
description: oxmysql is a database wrapper for FiveM.
show_downloads: true
color_scheme: dark
logo: "https://avatars.githubusercontent.com/u/88127058"
favicon: favicon.ico
